version: "3.8"

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jwt_security
    ports:
      - "5432:5432"
    networks:
      security-postgres-net:



  security:
    container_name: security
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      security-postgres-net:
    restart: on-failure

networks:
  security-postgres-net:

